######################################################################
##
## Filename: mux.udo
## Created on: Thu Jul 04 8:03:33 PM India Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
